### PR TITLE
Urgent fixes

### LINKED ISSUE #100: Fix overlap removal in 2024
Currently bugged due to the sample name changing to `DYto2E`, `DYto2Mu`, and `DYto2Tau`

### PR DESCRIPTION
**Pull request by jdgrassi**
Added the new naming convention to overlap removal. 
Fixed npv branches

Please prioritize reviewing and merging this short PR before the z_fitter rework PR.

### CODE REVIEW

**Review by jdgrassi — COMMENTED** [review]
Checked Anders B's additions, lgtm

**Review by andersbarzdukas — APPROVED** [review]
Tested with Run 2, 2022, and 2024 files. I checked the changes to pileup and met_tk variables. 

Everything looked good to me!

File: src/event_tools.cpp [hunk 1]
```diff
@@ -96,8 +96,10 @@ EventTools::EventTools(const string &name_, int year_, bool isData_, float nanoa
   if((Contains(name,"DYJetsToLL_M-50") || Contains(name,"DYJetsToLL_M-50")) && year<2022){ has_photon_in_sample = false; overlap_removal_key = "DYlowpt";}
   if((Contains(name,"DYJetsToLL_M-50") || Contains(name,"DYJetsToLL_M-50")) && year>=2022){ has_photon_in_sample = false; overlap_removal_key = "DY";}
   if(Contains(name,"DYto2L-2Jets_MLL-50_TuneCP5")){ has_photon_in_sample = false; overlap_removal_key = "DY";}
+  if(Contains(name, "DYto2E-2Jets_Bin-MLL-50_TuneCP5") || Contains(name, "DYto2Mu-2Jets_Bin-MLL-50_TuneCP5")){ has_photon_in_sample = false; overlap_removal_key = "DY";}
```
Comment (mcoshiro) [inline src/event_tools.cpp]: Missing "DYto2Tau" (probably pretty negligible after Z mass cut, but might as well add?)

File: src/process_nano.cxx [hunk 2]
```diff
@@ -387,7 +391,7 @@ int main(int argc, char *argv[]){
 
     //pileup energy density
     if (nanoaod_version >= 11 || nanoaod_version == 9.5)
-      pico.out_rho() = nano.fixedGridRhoAll();
+      pico.out_rho() = nano.Rho_fixedGridRhoAll();
```
Comment (mcoshiro) [inline src/process_nano.cxx]: This will probably break `NanoAODv9UCSB*` where the branch is called `fixedGridRhoAll`. Should split this check into `if (nanoaod_version == 9.5) ... else if (nanoaod_version >= 11)` and add `fxiedGridRhoAll` back to the pico variables

**Review by mcoshiro — COMMENTED** [review]
I have one minor comment on `DYto2Tau` and a concern that this will break `NanoAODv9UCSB*`. Other than that, looks good to me.

**Comment by jdgrassi** [comment]
Addressed Michael's comments. Merging
